image: "ubuntu:latest"

before_script:
    - apt update -qq && apt install -y pkg-config googletest build-essential

test:
    stage: build
    script:
        - make test
        - cd test && ./check
