image: "ubuntu:rolling"

before_script:
    - apt update -qq && apt install -y build-essential cmake git

test:
    stage: build
    script:
        - mkdir build && cd build && cmake .. && make && make test
